FROM titan/python-env:1.0

RUN cd / && mkdir app
ADD src /app
ADD static/requirements.txt /
ADD script/entrypoint.sh /

RUN chmod +x entrypoint.sh \
    && pip install -r requirements.txt

ENTRYPOINT [ "/entrypoint.sh" ]
