FROM python:3.8-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk update && apk add --no-cache bash build-base coreutils
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && python -m pip install --upgrade pip \
    && pip install -U setuptools pip

RUN cd / && mkdir app
ADD src /app
ADD script/entrypoint.sh /
RUN chmod +x entrypoint.sh

RUN cd /app && pip install -r requiretments.txt && pip install uvicorn[standard]

ENTRYPOINT [ "/entrypoint.sh" ]
